/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import java.sql.Connection;
import util.ConnectionFactory;





public class App {
       public static void main(String[] args) {
           
           //pedir a conexão para conectionnFactory
           Connection c = ConnectionFactory.getConnection();
           
           //encerra a conexão
           ConnectionFactory.closeConnection(c);
           
    }
}
